default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "postgres") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "postgres") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "postgres") %>_production
